prosessering:
  rolle: "928636f4-fd0d-4149-978e-a6fb68bb19de" # 0000-GA-STDAPPS

godkjente-leverandorer:
  ider:
    - "0192:310028142" # HUMAN DEDIKERT ISBJÃ˜RN SA
    - "0192:982410339" # VISMA preprod-org